# ELASTICSEARCH
elasticsearch:
  host: 20.124.20.151
  port: 9200

# SWAGGER
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /v1/api-docs
# Logging
logging:
  file:
    name: /Users/nageshchauhan/logs/sbe.log
  level:
    root: DEBUG
    com.cb: DEBUG
